/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

/**
 *
 * @author ESFOT
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        lblTipo.setVisible(false);
        txtTipo.setVisible(false);
        lblCapacidadColor.setVisible(false);          
        txtCapacidadColor.setVisible(false);          
        lblRAMVelocidad.setVisible(false);
        txtRAMVelocidad.setVisible(false);
        lblProcesador.setVisible(false);
        txtProcesador.setVisible(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProductos = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtCapacidadColor = new javax.swing.JTextField();
        txtRAMVelocidad = new javax.swing.JTextField();
        txtProcesador = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblCapacidadColor = new javax.swing.JLabel();
        lblRAMVelocidad = new javax.swing.JLabel();
        lblProcesador = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computador", "Accesorios", "Componentes" }));
        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        lblPrecio.setText("Precio:");

        lblMarca.setText("Marca:");

        lblTipo.setText("Tipo:");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblPrecio)
                    .addComponent(lblMarca)
                    .addComponent(lblTipo)
                    .addComponent(lblCapacidadColor)
                    .addComponent(lblRAMVelocidad)
                    .addComponent(lblProcesador))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProcesador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRAMVelocidad)
                    .addComponent(txtCapacidadColor)
                    .addComponent(txtTipo)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio)
                    .addComponent(txtMarca))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cmbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombre))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPrecio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMarca))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTipo))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(8, 8, 8)))
                                .addComponent(txtCapacidadColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCapacidadColor))
                        .addGap(18, 18, 18)
                        .addComponent(txtRAMVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRAMVelocidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProcesador))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
        String comboSel=cmbProductos.getSelectedItem().toString();
        lblTipo.setVisible(true);
        txtTipo.setVisible(true);
        if(comboSel.equals("Computador")){
            lblCapacidadColor.setVisible(true);
            lblCapacidadColor.setText("Capacidad \nAlmacenamiento");
            lblRAMVelocidad.setVisible(true);
            lblRAMVelocidad.setText("RAM:");
            lblProcesador.setVisible(true);
            lblProcesador.setText("Procesador:");
            txtCapacidadColor.setVisible(true);
            txtRAMVelocidad.setVisible(true);
            txtProcesador.setVisible(true);
        }else if(comboSel.equals("Accesorios")){
            lblCapacidadColor.setVisible(true);
            lblCapacidadColor.setText("Color:");
            lblRAMVelocidad.setVisible(false);           
            lblProcesador.setVisible(false);
            txtCapacidadColor.setVisible(true);
            txtRAMVelocidad.setVisible(false);
            txtProcesador.setVisible(false);
            
        }else if(comboSel.equals("Componentes")){
            lblCapacidadColor.setVisible(true);
            lblCapacidadColor.setText("Capacidad:");
            lblRAMVelocidad.setVisible(true);
            lblRAMVelocidad.setText("Velocidad:");
            lblProcesador.setVisible(false);
            txtCapacidadColor.setVisible(true);
            txtRAMVelocidad.setVisible(true);
            txtProcesador.setVisible(false);
            
        }
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String prodSel=cmbProductos.getSelectedItem().toString();
      String nombre= txtNombre.getText();
      double precio=Double.parseDouble(txtNombre.getText());
      String marca= txtNombre.getText();
      if(prodSel.equals("Computador")){
      String tipo=txtTipo.getText();
      int capacidad=Integer.parseInt( txtCapacidadColor.getText());
      int RAM= Integer.parseInt(txtRAMVelocidad.getText());
      String procesador=txtProcesador.getText();
         //Computador ProdCom=new Computador(); 
      }else if(prodSel.equals("Accesorios")){
          
      }else if(prodSel.equals("Componentes")){}
        
         

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCapacidadColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProcesador;
    private javax.swing.JLabel lblRAMVelocidad;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCapacidadColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProcesador;
    private javax.swing.JTextField txtRAMVelocidad;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
